Fixes and updates to make the module work
CyberReasoningSystem/attack_surface_approximation pull request #8
Opened 2024-12-26 14:19 UTC by razvand

Add configuration fixes to make the `attack_surface_approximation` module work. Improve instructions on using the module.

2024-12-26 21:16 UTC, ClaraStefania reviewed
I suggested a few small changes, one that solves an error and two in the README file.

2024-12-26 21:16 UTC, ClaraStefania commented on README.md
> +It extracts information and apply heuristics to determine if a given input stream is present.
```suggestion
It extracts information and applies heuristics to determine if a given input stream is present.
```

2024-12-26 21:16 UTC, ClaraStefania commented on README.md
> +     you should get something a path ending with `.venv/bin/poetry`.
```suggestion
     you should get a path ending with `.venv/bin/poetry`.
```

2024-12-26 21:16 UTC, ClaraStefania commented on attack_surface_approximation/dictionaries_generators/heuristics/man_parsing.py
The last line, 'return all_arguments', should be deleted. It is written twice and causes the error
```
SyntaxError: 'return' outside function
```

2024-12-27 11:04 UTC, ClaraStefania requested changes

2024-12-27 11:04 UTC, ClaraStefania commented on README.md
> +$ poetry run attack_surface_approximation fuzz  $(pwd)/../dataset/executables/toy_test_suite_1.elf --dictionary args.txt
```suggestion
$ poetry run attack_surface_approximation fuzz --elf $(pwd)/../dataset/executables/toy_test_suite_1.elf --dictionary args.txt
```

2024-12-27 15:08 UTC, ClaraStefania approved these changes

2025-01-09 21:13 UTC, AmaliaI12 requested changes

2025-01-09 21:13 UTC, AmaliaI12 commented on README.md
> +   This is an problem that may occur in certain situations, preventing Poetry from getting packages.
```suggestion
   This is a problem that may occur in certain situations, preventing Poetry from getting packages.
```

2025-08-30 11:13 UTC, AmaliaI12 approved these changes

2026-05-18 15:29 UTC, merged